<a href="https://colab.research.google.com/github/643021273-8/python-_dataviz2023/blob/main/Pandas101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

## Meta data = Data that describtion data

ใช้อธิบายช้อมูล

## CSV = Comma Separated Values
ในการจะใส่ค่าแต่ละค่า จะใช้  comma ในการแย่ง

.csv = Comma Separated Values

data.go.th

# นำ Data เข้า
- upload to colab  # กรณีใช้เเค่ครั้งเดียว
- link with google drive

## upload to colab

In [6]:
data0 = pd.read_csv('/content/csv.csv')

FileNotFoundError: ignored

In [ ]:
data0

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
0,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ,1193000
1,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...,1100000
2,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข,3075000
3,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...,6240000
4,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...,2685000
...,...,...,...,...,...,...,...,...,...
687,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองผักกะเฉด,3686000
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000
691,งบเพิ่มเติม,1,66,50500000,สำนักงานเขตบางบอน,NaN,งบลงทุน,ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล,7578000

In [ ]:
data0.head()

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
0,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ,1193000
1,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...,1100000
2,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข,3075000
3,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...,6240000
4,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...,2685000

In [ ]:
data0.tail()

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
687,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองผักกะเฉด,3686000
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000
691,งบเพิ่มเติม,1,66,50500000,สำนักงานเขตบางบอน,NaN,งบลงทุน,ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล,7578000

In [ ]:
data0.shape

(692, 9)

In [ ]:
data0.describe()

         Issue_No  Fiscal_year  Department_code  Approved_buget
count  692.000000   692.000000     6.920000e+02    6.920000e+02
mean     0.333815    64.543353     4.534202e+07    1.482811e+06
std      0.474972     1.476149     1.303279e+07    2.464625e+06
min      0.000000    62.000000     1.100000e+07    0.000000e+00
25%      0.000000    63.000000     5.013000e+07    4.100000e+05
50%      0.000000    65.000000     5.023000e+07    5.980000e+05
75%      1.000000    66.000000     5.036000e+07    1.628250e+06
max      2.000000    66.000000     5.050000e+07    2.850000e+07

## link with google drive

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [10]:
from google.colab import drive
drive.mount('/content/drive')  # mount =  เชื่อมไดร์ฟ

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [11]:
data1 = pd.read_csv('/content/drive/MyDrive/DataViz23Data/csv.csv')
data1.head()

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
0,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ,1193000
1,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...,1100000
2,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข,3075000
3,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...,6240000
4,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...,2685000

In [12]:
data1.head(10)  # ดูหัวตาราง จากแถวบน 10 แถวแรก นับจาก 0-9

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
0,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ,1193000
1,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...,1100000
2,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข,3075000
3,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...,6240000
4,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...,2685000
5,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองราษฎร์สามัคคีจากคลองทวีวัฒนาถึงคลองม...,1207000
6,งบประจำปี,0,62,50130000,สำนักงานเขตมีนบุรี,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกลำรางโต๊ะรอด ตั้งแต่คลองสองต้นนุ่นถึงระย...,225400
7,งบประจำปี,0,62,50130000,สำนักงานเขตมีนบุรี,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกลำรางเลียบคลองบึงขวาง ตั้งแต่คลองบึงขวาง...,452500
8,งบประจำปี,0,62,50150000,สำนักงานเขตหนองจอก,28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต,งบลงทุน,ขุดลอกคลองลำแขก จากคลองลำปลาทิว \nถึงคลองลำตาเ...,447000
9,งบประจำปี,0,62,50150000,สำนักงานเขตหนองจอก,28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต,งบลงทุน,ขุดลอกคลองอู่ตะเภา จากคลองลำนกแขวก\nถึงคลองลำม...,497000

In [13]:
data1.tail(10) # ดูท้ายตาราง จากข้างล่าง

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
682,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางไทยเอราวัณ,3494000
683,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองหนึ่งตะวันตก,4330000
684,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองสองตะวันตก,9832000
685,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองกีบหมู,2925000
686,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองลำกะโหลก,3875000
687,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองผักกะเฉด,3686000
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000
691,งบเพิ่มเติม,1,66,50500000,สำนักงานเขตบางบอน,NaN,งบลงทุน,ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล,7578000

In [14]:
data1.shape # ดูขนาด กี่เเถวกี่หลัก

(692, 9)

In [15]:
data1.describe()

         Issue_No  Fiscal_year  Department_code  Approved_buget
count  692.000000   692.000000     6.920000e+02    6.920000e+02
mean     0.333815    64.543353     4.534202e+07    1.482811e+06
std      0.474972     1.476149     1.303279e+07    2.464625e+06
min      0.000000    62.000000     1.100000e+07    0.000000e+00
25%      0.000000    63.000000     5.013000e+07    4.100000e+05
50%      0.000000    65.000000     5.023000e+07    5.980000e+05
75%      1.000000    66.000000     5.036000e+07    1.628250e+06
max      2.000000    66.000000     5.050000e+07    2.850000e+07

NaN = Not a Number

# ชี้ค่าในตาราง (indexing)

##มุมมองตาราง df[columns] [rows]
Df คือ ดาต้าเฟรม เป็นชื่อ datastructure ที่ pandas ใช้

In [16]:
data1['Budget_resource']

0        งบประจำปี
1        งบประจำปี
2        งบประจำปี
3        งบประจำปี
4        งบประจำปี
          ...
687    งบเพิ่มเติม
688    งบเพิ่มเติม
689    งบเพิ่มเติม
690    งบเพิ่มเติม
691    งบเพิ่มเติม
Name: Budget_resource, Length: 692, dtype: object

In [17]:
data1['Budget_resource'][690]

'งบเพิ่มเติม'

In [18]:
data1['Budget_resource'][-3:-1]

689    งบเพิ่มเติม
690    งบเพิ่มเติม
Name: Budget_resource, dtype: object

In [19]:
 data1.iloc[6,5] # .iloc เปลี่ยนมุมมองเป็น np.arry  ชี้เป็นเเถว คอลัม ติดลบ สไลด์ได้

'12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี่ยวกับน้ำท่วม'

In [20]:
data1.columns

Index(['Budget_resource', 'Issue_No', 'Fiscal_year', 'Department_code',
       'Department', 'Core_budget_code', 'Expenditure_category', 'Item_name',
       'Approved_buget'],
      dtype='object')

In [21]:
data1[['Approved_buget','Item_name','Department']]

,Approved_buget,Item_name,Department
0,1193000,ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ,สำนักการระบายน้ำ
1,1100000,ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...,สำนักการระบายน้ำ
2,3075000,ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข,สำนักการระบายน้ำ
3,6240000,ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...,สำนักการระบายน้ำ
4,2685000,ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...,สำนักการระบายน้ำ
...,...,...,...
687,3686000,ขุดลอกคลองผักกะเฉด,สำนักงานเขตคลองสามวา
688,2575000,ขุดลอกคลองบึงทรายกองดิน,สำนักงานเขตคลองสามวา
689,689000,ขุดลอกลำรางซาฟารี,สำนักงานเขตคลองสามวา
690,464000,ขุดลอกลำรางตาจันทร์,สำนักงานเขตคลองสามวา
691,7578000,ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล,สำนักงานเขตบางบอน

In [22]:
data1[['Approved_buget','Item_name','Department']][6:11]

,Approved_buget,Item_name,Department
6,225400,ขุดลอกลำรางโต๊ะรอด ตั้งแต่คลองสองต้นนุ่นถึงระย...,สำนักงานเขตมีนบุรี
7,452500,ขุดลอกลำรางเลียบคลองบึงขวาง ตั้งแต่คลองบึงขวาง...,สำนักงานเขตมีนบุรี
8,447000,ขุดลอกคลองลำแขก จากคลองลำปลาทิว \nถึงคลองลำตาเ...,สำนักงานเขตหนองจอก
9,497000,ขุดลอกคลองอู่ตะเภา จากคลองลำนกแขวก\nถึงคลองลำม...,สำนักงานเขตหนองจอก
10,189500,ขุดลอกลำกระโดงตรงข้ามซอยเพชรเกษม 50,สำนักงานเขตภาษีเจริญ

##มุมมองแบบ array

In [23]:
data1.iloc[-6,5]

nan

In [24]:
 data1.iloc[0,0] #เปลี่ยนมุมมองเป็น np. array

'งบประจำปี'

# Table Slicing
ไม่ค่อยมีประสิทธิภาพ
ต้องทราบพิกัด

In [25]:
data1.iloc[-20 :,7:10]

                                             Item_name  Approved_buget
672  ขุดลอกลำกระโดงแยกคลองบางแวก (ตรงข้ามวัดบุณยประ...          472000
673  ขุดลอกลำกระโดงแยกคลองบางขี้แก้ง (หมู่บ้านเอเวอ...          492000
674                         ขุดลอกคลองแยกคลองตาเทียม 1          469000
675  ขุดลอกลำกระโดงระหว่างซอยเพชรเกษม 43 กับ ซอยเพช...          493000
676                          ขุดลอกคลองแยกคลองยายเพิ่ม          481000
677                    ขุดลอกลำกระโดงข้างหมู่บ้านวรนุช          492000
678                                    ขุดลอกคลองตาตี่          483000
679                        ขุดลอกลำกระโดงข้างเดอะมอลล์          462000
680                      ขุดลอกลำกระโดงข้างบ้านบางแค 2          499000
681                                   ขุดลอกลำรางตาเชย         3559000
682                              ขุดลอกลำรางไทยเอราวัณ         3494000
683                             ขุดลอกคลองหนึ่งตะวันตก         4330000
684                               ขุดลอกคลองสองตะวันตก         9832000
685                                   ขุดลอกคลองกีบหมู         2925000
686                                 ขุดลอกคลองลำกะโหลก         3875000
687                                 ขุดลอกคลองผักกะเฉด         3686000
688                            ขุดลอกคลองบึงทรายกองดิน         2575000
689                                  ขุดลอกลำรางซาฟารี          689000
690                                ขุดลอกลำรางตาจันทร์          464000
691          ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล         7578000

 ## table Query

##อยากได้รายการที่ได้รับอนุมัติงบเกิน 1 ล้านบาท
โดยที่โลจิกจะต้องมีจำนวนสมาชิกเท่ากับจำนวนแถวของ df

In [26]:
small_df = data1.iloc[-5:,:]
small_df

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
687,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองผักกะเฉด,3686000
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000
691,งบเพิ่มเติม,1,66,50500000,สำนักงานเขตบางบอน,NaN,งบลงทุน,ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล,7578000

In [27]:
small_df[[False,True,True,False,False]]

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000

##ปั้น list logic จากตาราง pandas

In [28]:
small_df['Approved_buget']<1000000

687    False
688    False
689     True
690     True
691    False
Name: Approved_buget, dtype: bool

In [29]:
small_df[small_df['Approved_buget']<1000000]

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000

## Quiz3 อยากได้รายการทั้งหมดที่ได้รับการอนุมัติงบทั้งหมดที่มากกว่า 1 ล้าน แต่ไม่เกิน 2 ล้านบาท

In [30]:
small_df1 = data1.iloc[1:691]
small_df1

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget
1,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...,1100000
2,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข,3075000
3,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...,6240000
4,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...,2685000
5,งบประจำปี,0,62,11000000,สำนักการระบายน้ำ,12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...,งบลงทุน,ขุดลอกคลองราษฎร์สามัคคีจากคลองทวีวัฒนาถึงคลองม...,1207000
...,...,...,...,...,...,...,...,...,...
686,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองลำกะโหลก,3875000
687,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองผักกะเฉด,3686000
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000

In [31]:
small_df1[(small_df['Approved_buget']> 1000000) & (small_df1['Approved_buget']< 2000000)]
print(small_df1)

    Budget_resource  Issue_No  Fiscal_year  Department_code  \
1         งบประจำปี         0           62         11000000
2         งบประจำปี         0           62         11000000
3         งบประจำปี         0           62         11000000
4         งบประจำปี         0           62         11000000
5         งบประจำปี         0           62         11000000
..              ...       ...          ...              ...
686     งบเพิ่มเติม         1           66         50460000
687     งบเพิ่มเติม         1           66         50460000
688     งบเพิ่มเติม         1           66         50460000
689     งบเพิ่มเติม         1           66         50460000
690     งบเพิ่มเติม         1           66         50460000

               Department                                   Core_budget_code  \
1        สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...
2        สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...
3        สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...
4        สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...
5        สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...
..                    ...                                                ...
686  สำนักงานเขตคลองสามวา                                                NaN
687  สำนักงานเขตคลองสามวา                                                NaN
688  สำนักงานเขตคลองสามวา                                                NaN
689  สำนักงานเขตคลองสามวา                                                NaN
690  สำนักงานเขตคลองสามวา                                                NaN

    Expenditure_category                                          Item_name  \
1                งบลงทุน  ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...
2                งบลงทุน          ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข
3                งบลงทุน  ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...
4                งบลงทุน  ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...
5                งบลงทุน  ขุดลอกคลองราษฎร์สามัคคีจากคลองทวีวัฒนาถึงคลองม...
..                   ...                                                ...
686              งบลงทุน                                 ขุดลอกคลองลำกะโหลก
687              งบลงทุน                                 ขุดลอกคลองผักกะเฉด
688              งบลงทุน                            ขุดลอกคลองบึงทรายกองดิน
689              งบลงทุน                                  ขุดลอกลำรางซาฟารี
690              งบลงทุน                                ขุดลอกลำรางตาจันทร์

     Approved_buget
1           1100000
2           3075000
3           6240000
4           2685000
5           1207000
..              ...
686         3875000
687         3686000
688         2575000
689          689000
690          464000

[690 rows x 9 columns]

<ipython-input-31-9fdc1eb5d435>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  small_df1[(small_df['Approved_buget']> 1000000) & (small_df1['Approved_buget']< 2000000)]

# Quiz 4
1. ราคาเฉลี่ยของบ้านที่มีราคาระหว่าง 3-5 ร้านบาท
2. พื้นที่ และ จำนวนห้องนอนของบ้านที่แพงที่สุด
3. จำนวนที่จอดรถและห้องน้ำของบ้านที่ถูกที่สุด
4. ชนิดของบ้านที่แพงที่สุด
5. บ้านชนิดไหนมีปริมาณมากที่สุด

## load data to memory

In [ ]:
min_data1 = data1['Approved_buget'].min()
max_data1 =data1['Approved_buget'].max()
data1[(data1['Approved_buget'] == max_data1)| (data1['Approved_buget'] == min_data1)]

##2ให้เลือกรายการขุดลอกคูคลองของสำนักงานขุดลอกคูคลองของสำนักงานเขตคลองสานและ สำนักงานเขตคลองสามวา

In [ ]:
data1[(data1['Department'] == 'สำนักงานเขตคลองสาน') | (data1['Department'] == 'สำนักงานเขตคลองสามวา')]

In [ ]:
data1[(data1['Department'] == 'สำนักงานเขตคลองสาน') | (data1['Department'] == 'สำนักงานเขตคลองสามวา')].shape

##3จากข้อ 2 เขตไหนใช้งบประมาณเยอะกว่ากัน

In [ ]:
dataHW3 = data1[(data1['Department'] == 'สำนักงานเขตคลองสาน') | (data1['Department'] == 'สำนักงานเขตคลองสามวา')]

In [ ]:
dataHW3[['Budget_resource', 'Issue_No', 'Fiscal_year', 'Department_code',
       'Department', 'Core_budget_code', 'Expenditure_category', 'Item_name',
       'Approved_buget']].max()

In [ ]:
MAX_DATA3 = dataHW3['Approved_buget'].max()
dataMAX = dataHW3[(dataHW3['Approved_buget'] == MAX_DATA3)]
dataMAX

##4 core budget ไหน ในระหว่าง '12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี่ยวกับน้ำท่วม',
 '17-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายเพื่อการพัฒนากรุงเทพมหานคร',
 '28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต'มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติถูกที่สุด

In [ ]:
nonna_data1 = data1.dropna()
hascore_data1 = nonna_data1[nonna_data1['Core_budget_code'] != '-']
hascore_data1_12 =hascore_data1[hascore_data1['Core_budget_code'] == '12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี่ยวกับน้ำท่วม']
hascore_data1_28 =hascore_data1[hascore_data1['Core_budget_code'] == '28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต']
hascore_data1_17 =hascore_data1[hascore_data1['Core_budget_code'] == '17-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายเพื่อการพัฒนากรุงเทพมหานคร']
corename = []
x=set(hascore_data1['Core_budget_code'])
for n in x:
  corename.append(n)
hascore_data1_12_MEAN =hascore_data1_12['Approved_buget'].mean()
hascore_data1_17_MEAN =hascore_data1_17['Approved_buget'].mean()
hascore_data1_28_MEAN =hascore_data1_28['Approved_buget'].mean()
if (hascore_data1_12_MEAN > hascore_data1_17_MEAN ) & (hascore_data1_12_MEAN > hascore_data1_28_MEAN ):
  print(f'รายการนี้ {corename[0]} มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด {hascore_data1_12_MEAN}')
elif (hascore_data1_17_MEAN > hascore_data1_12_MEAN ) & (hascore_data1_17_MEAN > hascore_data1_28_MEAN ):
  print(f'รายการนี้ {corename[1]} มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด {hascore_data1_17_MEAN}')
elif (hascore_data1_28_MEAN > hascore_data1_12_MEAN ) & (hascore_data1_28_MEAN > hascore_data1_17_MEAN ):
  print(f'รายการนี้ {corename[2]} มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด {hascore_data1_28_MEAN}')

##1  รายการที่แพงที่สุดและถูกที่สุด

### 2. update ตารางด้วยตัวแปร ```inplace```

In [ ]:
this_data.dropna(subset=['sex','age'],inplace=True)

In [ ]:
this_data.isnull().any()

In [ ]:
aa = this_data.dropna(subset=['sex','age'],inplace=True)

In [ ]:
aa

### แทน missing ด้วยค่าที่เหมาะสม (```fillna()```)

In [ ]:
this_data = data_covid[['sex','age','province_of_onset']]

In [ ]:
this_data

In [ ]:
print(f'จำนวน record ก่อน drop missing ใน province {this_data.shape[0]}')
print(f'จำนวน record หลัง drop missing ใน province {this_data.dropna(subset=["province_of_onset"]).shape[0]}')

### 1. แทนด้วย class ใหม่

In [ ]:
this_data_updated = this_data.fillna(value={'sex':'ไม่รู้', 'age':-99, 'province_of_onset':'ไม่รู้'})
this_data_updated.head()

In [ ]:
this_data_updated.tail(15)

In [ ]:
this_data_updated.isnull().any()

### 2. แทนด้วยค่าที่เหมาะสม


*   ตามใจคนทำ
*   ค่ากลาง

#### ตามใจคนทำ

In [ ]:
data_covid.head()

In [ ]:
data_covid_fillasiwant = data_covid.fillna(value={'sex':'หญิง'})  #เรามีข้อมูลว่า เพศหญิงมีเยอะกว่าเพศชาย

In [ ]:
data_covid_fillasiwant.isnull().any()

#### แทนด้วยค่ากลาง

In [ ]:
data_covid['age']

In [ ]:
data_covid['age'].mean()

In [ ]:
data_covid_fillwithmean = data_covid.fillna(value={'age':data_covid['age'].mean()})

In [ ]:
data_covid_fillwithmean.isnull().any()

### การวนลูป record ในตาราง  (```.iterrows```)

In [ ]:
this_data = data_covid[['sex','age','province_of_onset']]
this_data

In [ ]:
for each_row in this_data.iterrows():
    # print(each_row)
    # print(each_row[1])
    # print(each_row[1]['sex'])
    if (each_row[1]['age'] <= 20) and (each_row[1]['province_of_onset'] == 'ขอนแก่น'):
        print(each_row)

### การวนลูป แบบมองตารางแพนด้าส์(pandas dataframe) เป็น numpy array  (```.iloc```)

In [ ]:
for each_row in range(this_data.shape[0]):
    if (this_data.iloc[each_row,1] <= 20) and (this_data.iloc[each_row,2] == 'ขอนแก่น'):  #each_row คือ ตัวเลข
        print(each_row)
        print(this_data.iloc[each_row,:])

## Quiz ตัดตารางออกมาเฉพาะปี 2021 ```announce_date``` ในปี 2021

**Hint**
*   วนลูปหา index ของปี 2021
*   ตัดตารางมาเฉพาะ ปี 2021

In [ ]:
TF=list()
for each_row in data_covid.iterrows():
    if each_row[1]['announce_date'].split('/')[2] == '2021':
        TF.append(True)
    else:
        TF.append(False)

data_covid[TF].head()

In [ ]:
TF

### HW กลุ่ม 2 || เลือกข้อมูลมาเฉพาะวัน announce_date เป็นวันที่ 1-20

# Function ตัวช่วยใน pandas

### ```.describe()``` คำนวณค่าทางสถิติของข้อมูลที่เป็นตัวเลข

In [ ]:
data_covid.describe()

### ```.mean()``` คำนวณค่าเฉลี่ยของข้อมูลโดยไม่สนใจ missing

In [ ]:
data_covid[data_covid['sex']=='ชาย']['age'].mean()

### ```.isnull()```

##การสร้าง colum เพิ่ม
``` df['ชื่อ คอลั่มใหม่]```

In [33]:
small_df['ผู้รับผิดชอบ'] = ['ลุงตู่','ลุงตู่','ลุงป้อม','ชัชชาติ','พิธา']

<ipython-input-33-0c6fae2e4445>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  small_df['ผู้รับผิดชอบ'] = ['ลุงตู่','ลุงตู่','ลุงป้อม','ชัชชาติ','พิธา']

In [34]:
small_df

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Core_budget_code,Expenditure_category,Item_name,Approved_buget,ผู้รับผิดชอบ
687,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองผักกะเฉด,3686000,ลุงตู่
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000,ลุงตู่
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางซาฟารี,689000,ลุงป้อม
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,NaN,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000,ชัชชาติ
691,งบเพิ่มเติม,1,66,50500000,สำนักงานเขตบางบอน,NaN,งบลงทุน,ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล,7578000,พิธา

##ลบคอลั่ม

In [40]:
small_df.drop(axis=1,columns=['Core_budget_code'])

,Budget_resource,Issue_No,Fiscal_year,Department_code,Department,Expenditure_category,Item_name,Approved_buget,ผู้รับผิดชอบ
687,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,งบลงทุน,ขุดลอกคลองผักกะเฉด,3686000,ลุงตู่
688,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,งบลงทุน,ขุดลอกคลองบึงทรายกองดิน,2575000,ลุงตู่
689,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,งบลงทุน,ขุดลอกลำรางซาฟารี,689000,ลุงป้อม
690,งบเพิ่มเติม,1,66,50460000,สำนักงานเขตคลองสามวา,งบลงทุน,ขุดลอกลำรางตาจันทร์,464000,ชัชชาติ
691,งบเพิ่มเติม,1,66,50500000,สำนักงานเขตบางบอน,งบลงทุน,ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล,7578000,พิธา

In [46]:
new_column = list()
for row in data1.iterrows():
  new_col = f"{row[1]['Department']}-{row[1]['Expenditure_category']}-{row[1]['Item_name']}"
  new_column.append(new_col)

In [47]:

data1['desciption'] = new_column
data1=data1.drop(axis=1,columns=['Department','Expenditure_category','Item_name'])